-- Player 기준 canonical 국가명으로 player / fmplayer 양쪽 기존 데이터를 정렬한다.
-- 목적: birth + nation_name 후보 조회에서 소스별 국가명 alias 때문에 후보가 끊기는 케이스를 줄인다.

UPDATE player
SET nation_name = UPPER(nation_name)
WHERE nation_name IS NOT NULL
  AND nation_name <> UPPER(nation_name);

UPDATE fmplayer
SET nation_name = UPPER(nation_name)
WHERE nation_name IS NOT NULL
  AND nation_name <> UPPER(nation_name);

UPDATE player p
SET p.nation_name = CASE p.nation_name
    WHEN 'THE NETHERLANDS' THEN 'NETHERLANDS'
    WHEN 'COTE D''IVOIRE' THEN 'CÔTE D''IVOIRE'
    WHEN 'IVORY COAST' THEN 'CÔTE D''IVOIRE'
    WHEN 'BOSNIA-HERZEGOVINA' THEN 'BOSNIA AND HERZEGOVINA'
    WHEN 'DEMOCRATIC REPUBLIC OF CONGO' THEN 'CONGO DR'
    WHEN 'CAPE VERDE' THEN 'CAPE VERDE ISLANDS'
    WHEN 'CURACAO' THEN 'CURAÇAO'
    WHEN 'SAO TOME E PRINCIPE' THEN 'SÃO TOMÉ E PRÍNCIPE'
    WHEN 'HONG KONG' THEN 'HONG KONG, CHINA'
    WHEN 'UNITED STATES' THEN 'USA'
    WHEN 'SWAZILAND' THEN 'ESWATINI'
    WHEN 'THE GAMBIA' THEN 'GAMBIA'
    WHEN 'CHINESE TAIPEI (CHINA PR)' THEN 'CHINESE TAIPEI'
    WHEN 'BRUNEI' THEN 'BRUNEI DARUSSALAM'
    WHEN 'MACAU' THEN 'MACAO'
    ELSE p.nation_name
END
WHERE p.nation_name IN (
    'THE NETHERLANDS',
    'COTE D''IVOIRE',
    'IVORY COAST',
    'BOSNIA-HERZEGOVINA',
    'DEMOCRATIC REPUBLIC OF CONGO',
    'CAPE VERDE',
    'CURACAO',
    'SAO TOME E PRINCIPE',
    'HONG KONG',
    'UNITED STATES',
    'SWAZILAND',
    'THE GAMBIA',
    'CHINESE TAIPEI (CHINA PR)',
    'BRUNEI',
    'MACAU'
);

UPDATE fmplayer fm
SET fm.nation_name = CASE fm.nation_name
    WHEN 'THE NETHERLANDS' THEN 'NETHERLANDS'
    WHEN 'COTE D''IVOIRE' THEN 'CÔTE D''IVOIRE'
    WHEN 'IVORY COAST' THEN 'CÔTE D''IVOIRE'
    WHEN 'BOSNIA-HERZEGOVINA' THEN 'BOSNIA AND HERZEGOVINA'
    WHEN 'DEMOCRATIC REPUBLIC OF CONGO' THEN 'CONGO DR'
    WHEN 'CAPE VERDE' THEN 'CAPE VERDE ISLANDS'
    WHEN 'CURACAO' THEN 'CURAÇAO'
    WHEN 'SAO TOME E PRINCIPE' THEN 'SÃO TOMÉ E PRÍNCIPE'
    WHEN 'HONG KONG' THEN 'HONG KONG, CHINA'
    WHEN 'UNITED STATES' THEN 'USA'
    WHEN 'SWAZILAND' THEN 'ESWATINI'
    WHEN 'THE GAMBIA' THEN 'GAMBIA'
    WHEN 'CHINESE TAIPEI (CHINA PR)' THEN 'CHINESE TAIPEI'
    WHEN 'BRUNEI' THEN 'BRUNEI DARUSSALAM'
    WHEN 'MACAU' THEN 'MACAO'
    ELSE fm.nation_name
END
WHERE fm.nation_name IN (
    'THE NETHERLANDS',
    'COTE D''IVOIRE',
    'IVORY COAST',
    'BOSNIA-HERZEGOVINA',
    'DEMOCRATIC REPUBLIC OF CONGO',
    'CAPE VERDE',
    'CURACAO',
    'SAO TOME E PRINCIPE',
    'HONG KONG',
    'UNITED STATES',
    'SWAZILAND',
    'THE GAMBIA',
    'CHINESE TAIPEI (CHINA PR)',
    'BRUNEI',
    'MACAU'
);
